### ISSUE TITLE
Bug downloaded episode not saved as downloaded after exiting

### ISSUE THREAD

**Issue by domgud** [RainbowDog98/HorribleSubs-Anime-Parser#2]
When exiting the parser after downloading a new episode (pressing the x or alt f4) the parser doesn't save that the episode is downloaded and is displayed as not downloaded on the next launch

**Comment by RainbowDog98** [comment]
Thanks for informing me of this issue. I will fix it right away 😃

**Comment by RainbowDog98** [comment]
Hello, I have fixed your issue by introducing a closing event. You can see the changes in the e4a010f commit.
